version: '3.8'

services:
  todo-app-api:
    build: .
    restart: always
    ports:
      - "4653:3000"
    environment:
      - REDIS_URL=redis://172.16.183.3:6379/1
      - RAILS_ENV=production
    depends_on:
      - redis
    networks:
      todo-app-api-network:
        ipv4_address: 172.16.183.2

  todo-app-api-redis:
    image: redis:7.2-rc1-alpine
    container_name: todo-app-api-redis
    restart: always
    networks:
      todo-app-api-network:
        ipv4_address: 172.16.183.3

networks:
  todo-app-api-network:
    driver: bridge
    name: todo-app-api-network
    ipam:
      driver: default
      config:
        - subnet: "172.16.183.0/24"
